In [2]:
import pandas as pd

In [72]:
q4 = pd.read_csv("2024q4/num.txt", delimiter="\t", encoding="utf-8")
q3 = pd.read_csv("2024q3/num.txt", delimiter="\t", encoding="utf-8")

In [ ]:
print(q4["ddate"].value_counts().to_string())

ddate
20240930    1357187
20230930     811107
20231231     573950
20240630     187073
20230630     150222
             ...
19960229          1
20050630          1
20120531          1
20100630          1
20100131          1
Name: count, Length: 241, dtype: int64

In [71]:
date = 20240630
adsh =  "0001438133-24-000201"

smaller_q4 = q4[(q4["ddate"] == date) & (q4["adsh"] == adsh)].reset_index(drop=True)
smaller_q3 = q3[(q3["ddate"] == date) & (q3["adsh"] == adsh)].reset_index(drop=True)
print(smaller_q4[["tag", "value"]])
print(smaller_q3[["tag", "value"]])

                  tag         value
0  StockholdersEquity  2.338750e+08
1   SharesOutstanding  6.543500e+07
2  StockholdersEquity  1.260392e+09
3  StockholdersEquity  6.500000e+04
4  StockholdersEquity -1.253000e+06
5  StockholdersEquity -1.025329e+09
Empty DataFrame
Columns: [tag, value]
Index: []

In [44]:
prevdf = pd.read_csv("2024q3/num.txt", delimiter="\t", encoding="utf-8")
print(prevdf["ddate"].value_counts().to_string())

ddate
20240630    1365566
20230630     807635
20231231     585842
20240331     163307
20230331     129352
20221231     127684
20230930      47963
20240731      47409
20230731      36077
20240531      25574
20220630      21327
20230531      18325
20240430      18021
20211231      17974
20230430      13347
20220331      10597
20240131      10571
20220930       9764
20240229       8500
20231031       8126
20230831       5610
20230228       4462
20231130       4257
20230131       4133
20220531       3621
20221031       2990
20240831       2796
20220731       2592
20210630       2355
20221130       2209
20220430       1924
20201231       1706
20220831       1572
20210930        931
20210331        832
20211031        635
20210430        565
20220228        535
20211130        495
20210531        416
20210831        367
20210731        347
20210228        325
20220131        312
20191231        206
20210131        152
20200430        128
20200630        125
20201031        114
20241231        107
20201130        102
20240930         99
20200831         83
20181231         74
20200731         72
20190630         65
20200131         61
20200930         57
20191130         57
20200229         55
20200331         50
20200531         46
20081231         42
20190331         36
20191031         34
20181130         34
20171231         32
20190930         30
20190228         29
20151231         29
20180331         28
20180930         26
20161231         25
20170630         25
20190430         25
20170930         23
20190731         22
20150630         22
20180731         21
20180131         20
20180630         20
20180430         18
20180531         16
20190531         16
20140930         15
20170331         15
29230630         14
20170430         14
20160831         14
20241130         13
20161130         13
20180228         13
20171031         13
20190831         13
20180831         13
20131231         12
20160331         12
20160430         12
20170228         11
20241031         11
20111031         10
20140430         10
20141231          9
20150531          9
20181031          9
20061231          9
20140228          9
20160630          9
20141031          9
20160131          8
20170531          8
20110430          8
20160229          8
20170731          8
20110930          7
20151031          7
20060831          7
20130630          7
20140831          7
20140630          7
20170131          7
20171130          7
20250630          7
20160531          7
20131031          6
20250331          6
20130331          6
20100228          6
20160930          6
20190131          6
20170831          6
20031231          6
20120331          5
20121231          5
20160731          5
20150731          5
20250731          5
20150331          5
20151130          5
20260630          5
20140331          5
20130430          5
20130930          4
20100731          4
19941031          4
20141130          4
20161031          4
20080131          4
19990930          4
20150831          4
20340630          4
20000630          4
20150131          4
20150228          4
20050228          3
20080430          3
20270630          3
20111231          3
20101130          3
20130531          3
20110228          3
20121031          3
20261231          3
20251231          3
20091231          3
20140531          3
20100531          3
20120630          3
20070131          3
20280531          3
20090228          3
20000229          3
20040229          3
20000131          2
20100630          2
20050930          2
20140131          2
20110831          2
20100331          2
20131130          2
20050430          2
20250131          2
20030331          2
20260430          2
20270531          2
20150930          2
20250228          2
19970430          2
20250531          2
20100430          2
20090331          2
20051231          2
20250430          2
20071231          2
20010630          2
20010430          2
20290630          2
20280630          2
20110331          2
20001130          1
20030930          1
20011130          1
20120930          1
20130731          1
20060531          1
20060331          1
20280731          1
20280331          1
20120831          1
20291231          1
20050630          1
20060731          1
20090430          1
20081130          1
20120531          1
20140731          1
19960229          1
20130131          1
20091130          1
20070430          1
20270930          1
20120731          1
20040930          1
20070630          1
19931130          1
20250930          1
20300630          1
20101031          1
20100831          1
20120229          1
20251031          1
20271231          1
20100131          1
20040831          1
20010331          1
20091031          1
20121130          1
20071130          1
20130228          1
20030531          1
19941231          1
20270331          1
20050531          1
20070930          1
20261031          1
20150430          1
20290731          1

In [33]:
company = df[df["ddate"] == 20240930].reset_index(drop=True)

print(len(company))
print(company.loc[3,:])

1357187
adsh         0001438133-24-000201
tag         OtherAssetsNoncurrent
version              us-gaap/2024
ddate                    20240930
qtrs                            0
uom                           USD
segments                      NaN
coreg                         NaN
value                  36447000.0
footnote                      NaN
Name: 3, dtype: object

In [16]:
num = pd.read_csv("2024q4/sub.txt", delimiter="\t", encoding="utf-8")

In [17]:
comnum = num[num["adsh"] == "0000950170-24-120982"].reset_index(drop=True)
print(comnum)

                   adsh      cik                          name     sic  \
0  0000950170-24-120982  1660334  VERRICA PHARMACEUTICALS INC.  2834.0

  countryba stprba        cityba  zipba                  bas1       bas2  ...  \
0        US     PA  WEST CHESTER  19380  10 NORTH HIGH STREET  SUITE 200  ...

       period      fy  fp     filed               accepted prevrpt detail  \
0  20240930.0  2024.0  Q3  20241105  2024-11-04 18:25:00.0       0      1

                instance nciks  aciks
0  vrca-20240930_htm.xml     1    NaN

[1 rows x 36 columns]

In [ ]:
print(num.loc[1,:])

adsh               0000950170-24-122438
cik                             1720116
name                   RED VIOLET, INC.
sic                              7372.0
countryba                            US
stprba                               FL
cityba                       BOCA RATON
zipba                             33431
bas1          2650 NORTH MILITARY TRAIL
bas2                          SUITE 300
baph                         5617574000
countryma                            US
stprma                               FL
cityma                       BOCA RATON
zipma                             33431
mas1          2650 NORTH MILITARY TRAIL
mas2                          SUITE 300
countryinc                           US
stprinc                              DE
ein                           822408531
former                              NaN
changed                             NaN
afs                               4-NON
wksi                                  0
fye                              1231.0
form                               10-Q
period                       20240930.0
fy                               2024.0
fp                                   Q3
filed                          20241106
accepted          2024-11-06 16:55:00.0
prevrpt                               0
detail                                1
instance          rdvt-20240930_htm.xml
nciks                                 1
aciks                               NaN
Name: 1, dtype: object

: